'use client';

import { Children, cloneElement, isValidElement, useCallback, useEffect, useId, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { ChevronRight } from 'lucide-react';
import { api } from '@/lib/api';
import { useAuth } from '@/providers/auth-provider';
import { PageHeader } from '@/components/layout/page-header';
import { Modal } from '@/components/ui/modal';

type Row = Record<string, any>;
const names:Record<string,string>={enquiry:'Enquiries',quote:'Quotations',order:'Sales orders',project:'Machine projects'};
const stageHints:Record<string,string>={enquiry:'Capture customer demand',quote:'Price, approve and send',order:'Confirm accepted quotes',project:'Initiate and execute'};
const reports:Record<string,string>={pipeline:'Sales pipeline',conversion:'Quotation conversion',quotations:'Quotations by customer',orders:'Orders by month / customer',pending:'Pending orders',milestones:'Payment milestone schedule',intake:'Project intake'};
const requirementNames:Record<string,string>={intended_use:'Intended use',performance:'Capacity / performance',interfaces:'Interfaces',utilities:'Utilities',constraints:'Constraints',standards:'Standards',customer_items:'Customer-provided items'};
const textFields=['scope','exclusions','warranty','terms'];
const label=(s:string)=>s.replace(/_/g,' ').replace(/^./,x=>x.toUpperCase());
const date=(s:any)=>s?String(s).slice(0,10):'';
const value=(s:any)=>s==null?'—':typeof s==='object'?JSON.stringify(s):String(s);
const money=(n:any,currency:string)=>`${currency} ${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:4})}`;
const blankLine=()=>({line_key:crypto.randomUUID(),description:'',unit:'Nos',quantity:1,unit_price:0,discount_percent:0,tax_percent:0});
const button='btn-secondary text-sm';

async function download(path:string,filename:string){
  const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL||'http://localhost:4051/api'}${path}`,{headers:{Authorization:`Bearer ${localStorage.getItem('machineiq_token')}`}});
  if(!response.ok){const body=await response.json().catch(()=>({message:'Download failed'}));throw new Error(body.message||'Download failed');}
  const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function Field({title,children}:{title:string;children:React.ReactNode}){
  const id=useId();
  return <div className="block text-sm font-medium text-fg-secondary"><label htmlFor={id} className="mb-1.5 block">{title}</label>{Children.map(children,child=>isValidElement(child)&&['input','select','textarea'].includes(String(child.type))?cloneElement(child as React.ReactElement<{id:string}>,{id}):child)}</div>;
}
function ErrorBox({error}:{error:string}){return error?<div role="alert" className="rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null;}
function Badge({status}:{status:string}){return <span className="rounded-md bg-surface-secondary px-2 py-1 text-xs font-semibold">{label(status)}</span>;}

function DocumentForm({record,config,onSave,onClose}:{record:Row;config:Row;onSave:(r:Row)=>void;onClose:()=>void}){
  const [form,setForm]=useState<Row>(()=>({...record,kind:record.kind==='order'?'quote':record.kind,lines:(record.lines||[]).map((l:Row)=>({...l,quantity:Number(l.quantity),unit_price:Number(l.unit_price),discount_percent:Number(l.discount_percent),tax_percent:Number(l.tax_percent)})),milestones:(record.milestones||[]).map((m:Row)=>({...m,amount:Number(m.amount),due_date:date(m.due_date)}))}));
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[newSite,setNewSite]=useState(false),[site,setSite]=useState({name:'',address:'',contact:''}),[sites,setSites]=useState<Row[]>(config.sites);
  const [activeTab,setActiveTab]=useState('basics');
  const set=(key:string,v:any)=>{if(error)setError('');setForm(f=>({...f,[key]:v}));};
  const lineSet=(i:number,key:string,v:any)=>setForm(f=>({...f,lines:f.lines.map((l:Row,j:number)=>j===i?{...l,[key]:v}:l)}));
  const validate=():{tab:string;message:string}|null=>{
    if(!form.title?.trim())return{tab:'basics',message:'Title is required.'};
    if(!form.customer_id)return{tab:'basics',message:'Customer is required.'};
    if(!form.owner_id)return{tab:'basics',message:'Owner is required.'};
    if(!(Number(form.quantity)>0))return{tab:'basics',message:'Machine quantity must be greater than zero.'};
    if(!form.document_date)return{tab:'basics',message:'Document date is required.'};
    if(record.kind!=='order')for(let i=0;i<form.lines.length;i++){const l=form.lines[i];
      if(!l.description?.trim())return{tab:'lines',message:`Line ${i+1} needs a description.`};
      if(!String(l.unit||'').trim())return{tab:'lines',message:`Line ${i+1} needs a unit.`};
      if(!(Number(l.quantity)>0))return{tab:'lines',message:`Line ${i+1} quantity must be greater than zero.`};
    }
    return null;
  };
  const save=async(e:React.FormEvent)=>{e.preventDefault();const issue=validate();if(issue){setActiveTab(issue.tab);setError(issue.message);return;}setBusy(true);setError('');try{
    const payload:Row={};for(const k of ['kind','customer_id','owner_id','title','machine_category','currency','scope','exclusions','warranty','terms','customer_po','inquiry_source','requirements'])payload[k]=form[k];
    payload.quantity=Number(form.quantity);for(const k of ['site_id','branch_id'])if(form[k])payload[k]=form[k];
    for(const k of ['document_date','valid_until','start_date','delivery_date'])if(form[k])payload[k]=date(form[k]);
    if(record.id)payload.version=record.version;
    payload.lines=form.lines.map((l:Row)=>{const r:Row={};for(const k of ['line_key','description','unit','quantity','unit_price','discount_percent','tax_percent'])r[k]=l[k];if(l.item_id)r.item_id=l.item_id;if(l.uom_id)r.uom_id=l.uom_id;return r;});
    payload.milestones=form.milestones.map((m:Row)=>({label:m.label,trigger:m.trigger,amount:Number(m.amount),...(m.due_date?{due_date:date(m.due_date)}:{})}));
    const result=record.id?await api.patch<Row>(`/sales/records/${record.id}`,payload):await api.post<Row>('/sales/records',payload);onSave(result);
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const isOrder=record.kind==='order';
  const requirementsFilled=Object.values(form.requirements||{}).filter((v:any)=>String(v||'').trim()).length;
  const commercialFilled=textFields.filter(k=>String(form[k]||'').trim()).length;
  const basicsDone=!!(form.title?.trim()&&form.customer_id&&form.owner_id&&Number(form.quantity)>0&&form.document_date);
  const tabs=[
    {key:'basics',label:'Basics & site',badge:basicsDone?'done':'pending'},
    {key:'requirements',label:'Requirements',badge:`${requirementsFilled}/${Object.keys(requirementNames).length}`},
    {key:'commercial',label:'Commercial scope',badge:`${commercialFilled}/${textFields.length}`},
    {key:'lines',label:'Quotation lines',badge:String(form.lines.length)},
    {key:'milestones',label:'Milestones',badge:String(form.milestones.length)},
  ];
  return <form onSubmit={save} noValidate className="space-y-5"><ErrorBox error={error}/><p className="text-sm text-fg-muted">Save a draft as you work. Complete the required site, dates, requirement summary and commercial terms before review.</p>
    <div role="tablist" aria-label="Document sections" className="flex flex-wrap gap-2 border-b border-border pb-3">{tabs.map(t=><button key={t.key} type="button" role="tab" aria-selected={activeTab===t.key} onClick={()=>setActiveTab(t.key)} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium transition ${activeTab===t.key?'bg-brand-600 text-white':'bg-surface-secondary text-fg-secondary hover:bg-surface-tertiary'}`}>{t.label}<span className={`rounded-full px-1.5 py-0.5 text-xs font-semibold ${activeTab===t.key?'bg-white/25':t.badge==='done'?'bg-green-100 text-green-700':'bg-surface-tertiary text-fg-muted'}`}>{t.badge==='done'?'✓':t.badge==='pending'?'·':t.badge}</span></button>)}</div>
    <div hidden={activeTab!=='basics'} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field title="Title"><input className="input-field" value={form.title} onChange={e=>set('title',e.target.value)}/></Field>
    <Field title="Customer"><select disabled={!!record.source_id} className="input-field" value={form.customer_id} onChange={e=>{set('customer_id',e.target.value);set('site_id','');}}><option value="">Select customer</option>{config.customers.map((c:Row)=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></Field>
    <Field title="Customer site"><select className="input-field" value={form.site_id||''} onChange={e=>set('site_id',e.target.value)}><option value="">Select site</option>{sites.filter((s:Row)=>s.customer_id===form.customer_id).map((s:Row)=><option key={s.id} value={s.id}>{s.name} · {s.address}</option>)}</select><button type="button" disabled={!form.customer_id} className="mt-1 text-brand-600" onClick={()=>setNewSite(!newSite)}>Add customer site</button></Field>
    <Field title="Owner"><select className="input-field" value={form.owner_id} onChange={e=>set('owner_id',e.target.value)}>{config.users.map((u:Row)=><option key={u.id} value={u.id}>{u.first_name} {u.last_name}</option>)}</select></Field>
    <Field title="Machine category"><input className="input-field" placeholder="e.g. Assembly, testing, packaging" value={form.machine_category} onChange={e=>set('machine_category',e.target.value)}/></Field>
    <Field title="Machine quantity"><input type="number" min="0.000001" step="0.000001" className="input-field" value={form.quantity} onChange={e=>set('quantity',e.target.value)}/></Field>
    <Field title="Branch"><select className="input-field" value={form.branch_id||''} onChange={e=>set('branch_id',e.target.value)}><option value="">Organization</option>{config.branches.map((b:Row)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>
    <Field title="Enquiry source"><input className="input-field" placeholder="Email, RFQ, site visit…" value={form.inquiry_source} onChange={e=>set('inquiry_source',e.target.value)}/></Field>
    {['document_date','valid_until','start_date','delivery_date'].map(k=><Field key={k} title={label(k)}><input type="date" className="input-field" value={date(form[k])} onChange={e=>set(k,e.target.value)}/></Field>)}</div>
    {newSite&&<div className="space-y-3 rounded-lg border border-border p-4"><h3 className="font-semibold">New customer site</h3>{['name','address','contact'].map(k=><Field key={k} title={`Site ${k}`}><input className="input-field" value={(site as Row)[k]} onChange={e=>setSite(s=>({...s,[k]:e.target.value}))}/></Field>)}<button type="button" className={button} onClick={async()=>{try{const s=await api.post<Row>('/sales/sites',{customer_id:form.customer_id,...site});setSites(x=>[...x,s]);set('site_id',s.id);setNewSite(false);}catch(e){setError((e as Error).message);}}}>Save site</button></div>}</div>
    <section hidden={activeTab!=='requirements'}><h3 className="mb-3 font-semibold">Requirement summary</h3><div className="grid gap-4 sm:grid-cols-2">{Object.entries(requirementNames).map(([k,title])=><Field key={k} title={title}><textarea className="input-field" rows={2} value={form.requirements?.[k]||''} onChange={e=>set('requirements',{...form.requirements,[k]:e.target.value})}/></Field>)}</div></section>
    <section hidden={activeTab!=='commercial'}><h3 className="mb-3 font-semibold">Commercial scope</h3><div className="grid gap-4 sm:grid-cols-2">{textFields.map(k=><Field key={k} title={label(k)}><textarea rows={2} className="input-field" value={form[k]} onChange={e=>set(k,e.target.value)}/></Field>)}<Field title="Customer PO reference"><input className="input-field" value={form.customer_po} onChange={e=>set('customer_po',e.target.value)}/></Field><Field title="Currency"><select disabled={!!record.source_id} className="input-field" value={form.currency} onChange={e=>set('currency',e.target.value)}>{Object.keys(config.settings.currencies).map(k=><option key={k}>{k}</option>)}</select></Field></div></section>
    <section hidden={activeTab!=='lines'} className="space-y-3"><h3 className="font-semibold">Quotation lines</h3>{isOrder&&<p className="text-sm text-fg-muted">Order lines are copied from the accepted quotation.</p>}{form.lines.map((l:Row,i:number)=><div className="space-y-3 rounded-lg border border-border p-4" key={l.line_key||i}><div className="grid gap-3 sm:grid-cols-2"><Field title={`Line ${i+1} item`}><select disabled={isOrder} className="input-field" value={l.item_id||''} onChange={e=>{const item=config.items.find((x:Row)=>x.id===e.target.value);if(item)setForm(f=>({...f,lines:f.lines.map((x:Row,j:number)=>j===i?{...x,item_id:item.id,uom_id:item.uom_id,description:item.name,unit:config.uoms.find((u:Row)=>u.id===item.uom_id)?.code||'',unit_price:Number(item.selling_price),tax_percent:Number(item.tax_percent)}:x)}));else lineSet(i,'item_id','');}}><option value="">Custom machine / service scope</option>{config.items.map((x:Row)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></Field><Field title={`Line ${i+1} description`}><input disabled={isOrder} className="input-field" value={l.description} onChange={e=>lineSet(i,'description',e.target.value)}/></Field></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{['unit','quantity','unit_price','discount_percent'].map(k=><Field key={k} title={`${label(k)} ${i+1}`}><input disabled={isOrder} type={k==='unit'?'text':'number'} min={k==='quantity'?'0.000001':'0'} step="0.000001" className="input-field" value={l[k]} onChange={e=>lineSet(i,k,k==='unit'?e.target.value:Number(e.target.value))}/></Field>)}<Field title={`Tax % ${i+1}`}><select disabled={isOrder} className="input-field" value={l.tax_percent} onChange={e=>lineSet(i,'tax_percent',Number(e.target.value))}>{config.settings.taxes.map((t:number)=><option key={t} value={t}>{t}%</option>)}</select></Field></div>{!isOrder&&<button type="button" className="text-sm text-red-600" onClick={()=>set('lines',form.lines.filter((_:Row,j:number)=>j!==i))}>Remove line {i+1}</button>}</div>)}{!isOrder&&<button type="button" className={button} onClick={()=>set('lines',[...form.lines,blankLine()])}>Add line</button>}<p className="text-sm text-fg-muted">Totals are calculated by the server using the configured currency precision.</p></section>
    <section hidden={activeTab!=='milestones'} className="space-y-3"><h3 className="font-semibold">Payment milestones · gross contract value</h3>{form.milestones.map((m:Row,i:number)=><div key={i} className="grid gap-3 rounded-lg border border-border p-4 sm:grid-cols-4">{['label','trigger','due_date','amount'].map(k=><Field key={k} title={`Milestone ${i+1} ${label(k)}`}><input className="input-field" type={k==='due_date'?'date':k==='amount'?'number':'text'} step="0.0001" min="0" value={m[k]||''} onChange={e=>set('milestones',form.milestones.map((x:Row,j:number)=>j===i?{...x,[k]:k==='amount'?Number(e.target.value):e.target.value}:x))}/></Field>)}<button type="button" className="text-left text-sm text-red-600" onClick={()=>set('milestones',form.milestones.filter((_:Row,j:number)=>j!==i))}>Remove milestone</button></div>)}<button type="button" className={button} onClick={()=>set('milestones',[...form.milestones,{label:'',trigger:'',due_date:'',amount:0}])}>Add payment milestone</button></section>
    <div className="sticky bottom-0 flex justify-end gap-3 border-t border-border bg-surface py-4"><button type="button" className={button} onClick={onClose}>Cancel</button><button disabled={busy} className="btn-primary">{busy?'Saving…':'Save draft'}</button></div>
  </form>;
}

export function SalesWorkspace({id}:{id?:string}) {
  const {user}=useAuth(),router=useRouter(),search=useSearchParams();
  const kind=search.get('kind')||'enquiry',tab=search.get('tab')||'records';
  const [config,setConfig]=useState<Row|null>(null),[record,setRecord]=useState<Row|null>(null),[data,setData]=useState<Row[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Row|null>(null);
  const [filters,setFilters]=useState<Row>({search:'',customer_id:'',status:'',from:'',to:'',owner_id:'',branch_id:''}),[offset,setOffset]=useState(0);
  const [action,setAction]=useState(''),[command,setCommand]=useState<Row>({}),[reportName,setReportName]=useState('pipeline'),[report,setReport]=useState<Row|null>(null),[comparison,setComparison]=useState<Row|null>(null),[comment,setComment]=useState(''),[communication,setCommunication]=useState(false),[notifications,setNotifications]=useState<Row[]>([]),[settingsOpen,setSettingsOpen]=useState(false),[settings,setSettings]=useState<Row>({});
  const query=useCallback(()=>new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,v])=>v).map(([k,v])=>[k,String(v)]))).toString(),[filters]);
  const loadSequence=useRef(0);
  const load=useCallback(async()=>{
    const sequence=++loadSequence.current;
    setBusy(true);setError('');
    try {
      const c=await api.get<Row>('/sales/config');
      // A mutation must not reuse a detail request that began before it committed.
      const path=id?`/sales/records/${id}?refresh=${Date.now()}-${sequence}`:tab==='reports'?`/sales/reports/${reportName}?${query()}`:tab==='alerts'?'/sales/notifications':`/sales/records?kind=${kind}&offset=${offset}&${query()}`;
      const result=await api.get<any>(path);
      if(sequence!==loadSequence.current)return;
      setConfig(c);setSettings(c.settings);
      if(id)setRecord(result);else if(tab==='reports')setReport(result);else if(tab==='alerts')setNotifications(result);else {setData(result.data);setTotal(result.total);}
    }catch(e){if(sequence===loadSequence.current)setError((e as Error).message);}
    finally{if(sequence===loadSequence.current)setBusy(false);}
  },[id,kind,tab,reportName,query,offset]);
  useEffect(()=>{void load();},[load]);
  const can=(permission:string)=>config?.permissions.includes(permission);
  const activeKind=id?record?.kind||'':kind;
  const activeStage=useRef<HTMLAnchorElement|null>(null);
  useEffect(()=>{activeStage.current?.scrollIntoView({block:'nearest',inline:'center'});},[activeKind]);
  const save=(r:Row)=>{setEditing(null);if(id===r.id){setRecord(r);void load();}else router.push(`/sales/${r.id}`);};
  const create=()=>{const today=new Date().toISOString().slice(0,10),valid=new Date(Date.now()+30*86400000).toISOString().slice(0,10);setEditing({kind:kind==='quote'?'quote':'enquiry',title:'',customer_id:'',site_id:'',owner_id:user?.id||'',machine_category:'',quantity:1,document_date:today,valid_until:valid,start_date:'',delivery_date:'',currency:config?.company.base_currency||'INR',scope:'',exclusions:'',warranty:'',terms:'',customer_po:'',inquiry_source:'',requirements:Object.fromEntries(Object.keys(requirementNames).map(k=>[k,''])),lines:kind==='quote'?[blankLine()]:[],milestones:[]});};
  const startAction=(name:string)=>{setAction(name);setCommand({request_key:crypto.randomUUID(),reason:'',evidence:'',customer_po:record?.customer_po||'',owner_id:record?.owner_id||'',title:record?.title||'',start_date:date(record?.start_date)||new Date().toISOString().slice(0,10),delivery_date:date(record?.delivery_date)});};
  const submitAction=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const body:Row={action,version:record?.version,request_key:command.request_key};for(const k of ['reason','evidence','customer_po'])if(command[k])body[k]=command[k];if(action==='project')for(const k of ['owner_id','title','start_date','delivery_date'])body[k]=command[k];const r=await api.post<Row>(`/sales/records/${id}/actions`,body);setAction('');save(r);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const actions:Record<string,string[]>={
    'enquiry:draft':['qualify','cancel'],'enquiry:new':['qualify','lose','cancel'],'enquiry:qualified':['quote','lose','cancel'],'enquiry:quoted':['quote','lose','cancel'],'enquiry:lost':['reopen'],
    'quote:draft':['submit','cancel'],'quote:review':['approve','return','reject','cancel'],'quote:approved':['send','revise','cancel'],'quote:sent':['accept','customer_reject','expire','revise','cancel'],'quote:accepted':['order','revise','cancel'],'quote:rejected':['revise'],'quote:expired':['revise'],
    'order:draft':['submit','cancel'],'order:review':['approve','return','reject','cancel'],'order:confirmed':['project','hold','revise','cancel'],'order:on_hold':['resume','revise','cancel'],
    'project:initiated':['activate','hold','cancel'],'project:active':['hold','cancel'],'project:on_hold':['resume','cancel'],
  };
  const actionLabel:Record<string,string>={quote:'Create quotation',order:'Create sales order',project:'Create machine project',revise:'New revision',approve:record?.kind==='order'?'Approve & confirm':'Approve',customer_reject:'Record customer rejection',accept:'Record customer acceptance',return:'Return for correction',submit:'Submit for approval',send:'Mark as sent'};
  const exportReport=async(format:string)=>{try{await download(`/sales/reports/${reportName}/export/${format}?${query()}`,`${reportName}.${format}`);}catch(e){setError((e as Error).message);}};
  return <div className="space-y-5 pb-10" data-testid="sales-workspace">
    <style>{`@media print { body * { visibility:hidden; } #sales-print, #sales-print * { visibility:visible; } #sales-print { position:absolute; inset:0; padding:24px; background:white; color:black; } .no-print { display:none!important; } }`}</style>
    <PageHeader title={id?record?.number||'Sales document':'Sales & Machine Projects'} description={id?`${label(record?.kind||'')} · revision ${record?.revision||1}`:'Customer demand, controlled quotations, approved orders and project initiation.'}/>
    <nav aria-label="Sales navigation" className="space-y-3 no-print">
      <ol className="flex items-center gap-1.5 overflow-x-auto pb-1">{Object.entries(names).map(([k,n],i)=><li key={k} className="flex shrink-0 items-center gap-1.5">{i>0&&<ChevronRight aria-hidden="true" className="h-4 w-4 shrink-0 text-fg-muted"/>}
        <Link href={`/sales?kind=${k}`} ref={activeKind===k?activeStage:undefined} aria-current={activeKind===k?'page':undefined} className={`flex items-center gap-2.5 rounded-xl border px-3.5 py-2.5 transition ${activeKind===k?'border-brand-500 bg-brand-50 dark:bg-brand-950/30':'border-border bg-surface hover:border-brand-500 hover:bg-surface-secondary'}`}>
          <span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold ${activeKind===k?'bg-brand-600 text-white':'bg-surface-secondary text-fg-muted'}`}>{i+1}</span>
          <span className="text-left"><span className={`block text-sm font-semibold ${activeKind===k?'text-brand-700 dark:text-brand-300':'text-fg'}`}>{n}</span><span className="block text-xs text-fg-muted">{stageHints[k]}</span></span>
        </Link></li>)}</ol>
      <div className="flex flex-wrap gap-2"><Link href="/sales?tab=reports" className={button}>Reports</Link><Link href="/sales?tab=alerts" className={button}>Sales alerts</Link>{can('administer')&&<button className={button} onClick={()=>setSettingsOpen(true)}>Sales settings</button>}</div>
    </nav>
    <ErrorBox error={error}/>{busy&&<p role="status" className="text-sm text-fg-muted">Loading…</p>}
    {!id&&tab!=='alerts'&&<div className="space-y-3 rounded-xl border border-border bg-surface p-4 no-print"><div className="grid gap-3 sm:grid-cols-3"><Field title="Search"><input className="input-field" placeholder="Number, title, customer or PO" value={filters.search} onChange={e=>{setOffset(0);setFilters(f=>({...f,search:e.target.value}));}}/></Field><Field title="Customer filter"><select className="input-field" value={filters.customer_id} onChange={e=>setFilters(f=>({...f,customer_id:e.target.value}))}><option value="">All customers</option>{config?.customers.map((c:Row)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field title="Status filter"><input className="input-field" placeholder="e.g. confirmed" value={filters.status} onChange={e=>setFilters(f=>({...f,status:e.target.value}))}/></Field>{['from','to'].map(k=><Field key={k} title={label(k)}><input type="date" className="input-field" value={filters[k]} onChange={e=>setFilters(f=>({...f,[k]:e.target.value}))}/></Field>)}<Field title="Owner filter"><select className="input-field" value={filters.owner_id} onChange={e=>setFilters(f=>({...f,owner_id:e.target.value}))}><option value="">All permitted owners</option>{config?.users.map((u:Row)=><option key={u.id} value={u.id}>{u.first_name} {u.last_name}</option>)}</select></Field></div><div className="flex flex-wrap gap-2"><button className={button} onClick={()=>localStorage.setItem(`sales-filters-${kind}-${tab}`,JSON.stringify(filters))}>Save filters</button><button className={button} onClick={()=>{try{setFilters(JSON.parse(localStorage.getItem(`sales-filters-${kind}-${tab}`)||'{}'));}catch{setError('Saved filters are invalid');}}}>Load saved filters</button><button className={button} onClick={()=>setFilters({search:'',customer_id:'',status:'',from:'',to:'',owner_id:''})}>Clear filters</button></div></div>}
    {!id&&tab==='records'&&<><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{names[kind]} <span className="text-fg-muted">({total})</span></h2>{can('create')&&['enquiry','quote'].includes(kind)&&<button className="btn-primary" onClick={create}>New {kind==='quote'?'quotation':'enquiry'}</button>}</div>{!data.length&&!busy&&<p className="rounded-xl border border-dashed border-border p-8 text-center text-fg-muted">No {names[kind]?.toLowerCase()} yet. {kind==='order'?'Create an order from an accepted quotation.':kind==='project'?'Create a project from an approved sales order.':'Create your first record to begin.'}</p>}<div className="grid gap-3 lg:grid-cols-2">{data.map(r=><Link href={`/sales/${r.id}`} key={r.id} className="rounded-xl border border-border bg-surface p-5 transition hover:border-brand-500"><div className="flex justify-between gap-3"><strong>{r.number} <span className="text-xs text-fg-muted">r{r.revision}</span></strong><Badge status={r.status}/></div><h3 className="mt-2 font-semibold">{r.title}</h3><p className="mt-1 text-sm text-fg-muted">{r.customer_name} · {r.owner_name}</p><div className="mt-3 flex justify-between text-sm"><span>{money(r.gross,r.currency)}</span><span>Delivery {date(r.delivery_date)||'Not set'}</span></div></Link>)}</div><div className="flex gap-3"><button disabled={!offset} className={button} onClick={()=>setOffset(Math.max(0,offset-30))}>Previous</button><button disabled={offset+30>=total} className={button} onClick={()=>setOffset(offset+30)}>Next</button></div></>}
    {!id&&tab==='alerts'&&<div className="space-y-3">{notifications.length===0&&<p>No sales alerts.</p>}{notifications.map(n=><div className="flex items-center justify-between gap-3 rounded-xl border border-border bg-surface p-4" key={n.id}><Link href={`/sales/${n.record_id}`}>{n.message}<span className="mt-1 block text-xs text-fg-muted">{new Date(n.created_at).toLocaleString()}</span></Link>{!n.read_at&&<button className={button} onClick={async()=>{try{await api.patch(`/sales/notifications/${n.id}/read`,{});void load();}catch(e){setError((e as Error).message);}}}>Mark read</button>}</div>)}</div>}
    {!id&&tab==='reports'&&<><div className="flex flex-wrap items-end gap-3 no-print"><Field title="Report"><select className="input-field" value={reportName} onChange={e=>setReportName(e.target.value)}>{Object.entries(reports).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></Field>{can('export')&&<><button className={button} onClick={()=>void exportReport('csv')}>Export CSV</button><button className={button} onClick={()=>void exportReport('xlsx')}>Export Excel</button><button className={button} onClick={async()=>{try{if(id)await api.post(`/sales/records/${id}/print`,{});else await api.post(`/sales/reports/${reportName}/print?${query()}`,{});window.print();}catch(e){setError((e as Error).message);}}}>Print / PDF</button></>}</div>{report&&<section id="sales-print" className="space-y-4 rounded-xl border border-border bg-surface p-5"><h2 className="text-xl font-semibold">{config?.company.name} · {reports[reportName]}</h2><p className="text-sm text-fg-secondary">{report.definition}</p><p className="text-xs text-fg-muted">Generated {new Date(report.generated_at).toLocaleString()} · {user?.firstName} {user?.lastName} · Filters: {Object.entries(report.filters).map(([k,v])=>`${k}: ${v}`).join(', ')||'All permitted records'}</p><DataTable rows={report.rows}/><h3 className="font-semibold">Supporting records</h3><div className="flex flex-wrap gap-2">{report.sources.map((r:Row)=><Link key={r.id} href={`/sales/${r.id}`} className="text-sm text-brand-600 underline">{r.number} · {r.customer}</Link>)}</div></section>}</>}
    {id&&record&&<><div className="flex flex-wrap gap-2 no-print">{can('edit')&&['draft','new'].includes(record.status)&&<button className="btn-primary" onClick={()=>setEditing(record)}>Edit draft</button>}{(actions[`${record.kind}:${record.status}`]||[]).filter(a=>can(['approve','return','reject'].includes(a)?'approve':a==='cancel'?'cancel':['quote','order','project','revise'].includes(a)?'create':'edit')).map(a=><button key={a} className={button} onClick={()=>startAction(a)}>{actionLabel[a]||label(a)}</button>)}{can('export')&&<button className={button} onClick={async()=>{try{if(id)await api.post(`/sales/records/${id}/print`,{});else await api.post(`/sales/reports/${reportName}/print?${query()}`,{});window.print();}catch(e){setError((e as Error).message);}}}>Print / PDF</button>}</div>
    <section id="sales-print" className="space-y-5 rounded-xl border border-border bg-surface p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-brand-600">{record.snapshot?.company?.name||config?.company.name}</p><h2 className="mt-1 text-2xl font-semibold">{record.number} · r{record.revision}</h2><p className="mt-1">{record.title}</p></div><div className="space-y-2 text-right"><Badge status={record.status}/><p className="text-sm">Approval: {label(record.approval)}</p></div></div><div className="grid gap-4 border-y border-border py-4 sm:grid-cols-3"><div><p className="text-xs text-fg-muted">Customer / site</p><p className="font-semibold">{record.customer_name}</p><p className="text-sm">{record.snapshot?.site?.name||config?.sites.find((s:Row)=>s.id===record.site_id)?.name||'Site not set'}</p></div><div><p className="text-xs text-fg-muted">Machine / quantity</p><p>{record.machine_category||'Not set'} · {Number(record.quantity)}</p></div><div><p className="text-xs text-fg-muted">Dates</p><p className="text-sm">Document: {date(record.document_date)}<br/>Validity: {date(record.valid_until)||'—'}<br/>Delivery: {date(record.delivery_date)||'—'}</p></div></div>
    <div className="flex flex-wrap gap-3 text-sm"><strong>Source trail:</strong>{record.source?<Link className="text-brand-600 underline" href={`/sales/${record.source.id}`}>{record.source.number} · r{record.source.revision}</Link>:<span>Original {record.kind}</span>}{record.downstream.map((d:Row)=><Link key={d.id} className="text-brand-600 underline" href={`/sales/${d.id}`}>{d.number} ({label(d.status)})</Link>)}</div>
    <div className="grid gap-4 sm:grid-cols-2">{textFields.map(k=><div key={k}><h3 className="text-sm font-semibold">{label(k)}</h3><p className="whitespace-pre-wrap text-sm text-fg-secondary">{record[k]||'Not set'}</p></div>)}</div>
    <DataTable rows={record.lines.map((l:Row)=>({description:l.description,unit:l.unit,quantity:l.quantity,unit_price:l.unit_price,discount_percent:l.discount_percent,tax_percent:l.tax_percent,net:l.net,tax:l.tax,gross:l.gross}))}/><div className="space-y-1 text-right"><p>Net {money(record.net,record.currency)}</p><p>Tax {money(record.tax,record.currency)}</p><p className="text-xl font-bold">Total {money(record.gross,record.currency)}</p></div>
    <h3 className="font-semibold">Payment milestone schedule</h3><DataTable rows={record.milestones.map((m:Row)=>({label:m.label,trigger:m.trigger,due_date:date(m.due_date),amount:money(m.amount,record.currency)}))}/><p className="text-xs text-fg-muted">Contractual schedule · gross value basis. Payment processing is part of the finance release.</p>
    <h3 className="font-semibold">Requirement summary</h3><div className="grid gap-3 sm:grid-cols-2">{Object.entries(requirementNames).map(([k,n])=><div key={k}><h4 className="text-sm font-semibold">{n}</h4><p className="whitespace-pre-wrap text-sm text-fg-secondary">{record.requirements[k]||'Not set'}</p></div>)}</div>
    {record.accepted_evidence&&<p className="rounded-lg bg-surface-secondary p-3 text-sm">Customer acceptance: {record.accepted_evidence}</p>}
    {record.kind==='project'&&<p className="rounded-lg bg-surface-secondary p-3 text-sm">Project baseline established from approved order {record.snapshot?.baseline?.sourceOrderNumber}. Owner, dates, scope, requirements and commercial milestones are retained.</p>}
    </section>
    <section className="space-y-3 rounded-xl border border-border bg-surface p-5 no-print"><h3 className="font-semibold">Revisions & comparison</h3><div className="flex flex-wrap gap-3">{record.revisions.map((r:Row)=><div key={r.id} className="flex items-center gap-2"><Link href={`/sales/${r.id}`} className="text-sm text-brand-600 underline">Revision {r.revision} · {label(r.status)}</Link>{r.id!==record.id&&<button className="btn-ghost text-xs" onClick={async()=>{try{setComparison(await api.get<Row>(`/sales/records/${r.id}/compare/${record.id}`));}catch(e){setError((e as Error).message);}}}>Compare</button>}</div>)}</div>{comparison&&<div className="space-y-3"><h4>Revision {comparison.from} → {comparison.to}</h4><DataTable rows={comparison.fields}/><h4>Added lines</h4><DataTable rows={comparison.added.map((l:Row)=>({description:l.description,quantity:l.quantity,unit_price:l.unit_price}))}/><h4>Removed lines</h4><DataTable rows={comparison.removed.map((l:Row)=>({description:l.description,quantity:l.quantity,unit_price:l.unit_price}))}/><h4>Changed lines</h4><DataTable rows={comparison.changed.map((l:Row)=>({before:l.before,after:l.after}))}/></div>}</section>
    <section className="space-y-3 rounded-xl border border-border bg-surface p-5 no-print"><h3 className="font-semibold">Commercial attachments</h3>{record.attachments.map((a:Row)=><button key={a.id} className="mr-3 text-sm text-brand-600 underline" onClick={async()=>{try{await download(`/sales/records/${a.record_id}/attachments/${a.id}`,a.name);}catch(e){setError((e as Error).message);}}}>{a.name} · {new Date(a.created_at).toLocaleDateString()}</button>)}{can('edit')&&<Field title="Upload evidence (PDF, PNG, JPEG · up to 8 MB)"><input type="file" accept="application/pdf,image/png,image/jpeg" className="input-field" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const form=new FormData();form.append('file',file);await api.postForm(`/sales/records/${record.id}/attachments`,form);void load();}catch(e){setError((e as Error).message);}}}/></Field>}</section>
    <section className="space-y-3 rounded-xl border border-border bg-surface p-5 no-print"><h3 className="font-semibold">Activity & customer communication</h3>{can('edit')&&<form className="space-y-2" onSubmit={async e=>{e.preventDefault();try{await api.post(`/sales/records/${record.id}/comments`,{type:communication?'communication':'comment',text:comment});setComment('');void load();}catch(e){setError((e as Error).message);}}}><Field title="Comment or communication note"><textarea required className="input-field" value={comment} onChange={e=>setComment(e.target.value)}/></Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={communication} onChange={e=>setCommunication(e.target.checked)}/>Customer communication</label><button className={button}>Add to activity</button></form>}{record.events.map((e:Row)=><div key={e.id} className="border-l-2 border-border pl-3 text-sm"><p><strong>{label(e.action)}</strong> · {e.actor_name} · {new Date(e.created_at).toLocaleString()}</p>{e.reason&&<p className="whitespace-pre-wrap text-fg-secondary">{e.reason}</p>}</div>)}</section>
    </>}
    {editing&&config&&<Modal title={editing.id?'Edit draft':`New ${editing.kind}`} onClose={()=>setEditing(null)} size="xl"><DocumentForm record={editing} config={config} onSave={save} onClose={()=>setEditing(null)}/></Modal>}
    {action&&<Modal title={actionLabel[action]||label(action)} onClose={()=>setAction('')}><form className="space-y-4" onSubmit={submitAction}><ErrorBox error={error}/><p className="text-sm text-fg-secondary">{record?.number} · revision {record?.revision}. This action is recorded in the activity history.</p>{['return','reject','customer_reject','lose','reopen','hold','resume','cancel','revise'].includes(action)&&<Field title="Reason"><textarea required className="input-field" value={command.reason} onChange={e=>setCommand(c=>({...c,reason:e.target.value}))}/></Field>}{action==='accept'&&<><Field title="Customer acceptance evidence / reference"><textarea required className="input-field" placeholder="Customer email, signed document or reference" value={command.evidence} onChange={e=>setCommand(c=>({...c,evidence:e.target.value}))}/></Field><Field title="Customer PO reference"><input className="input-field" value={command.customer_po} onChange={e=>setCommand(c=>({...c,customer_po:e.target.value}))}/></Field></>}{action==='project'&&<><Field title="Project name"><input required className="input-field" value={command.title} onChange={e=>setCommand(c=>({...c,title:e.target.value}))}/></Field><Field title="Project manager"><select required className="input-field" value={command.owner_id} onChange={e=>setCommand(c=>({...c,owner_id:e.target.value}))}><option value="">Select manager</option>{config?.users.filter((u:Row)=>['admin','manager'].includes(u.role)).map((u:Row)=><option key={u.id} value={u.id}>{u.first_name} {u.last_name}</option>)}</select></Field>{['start_date','delivery_date'].map(k=><Field key={k} title={label(k)}><input required type="date" className="input-field" value={command[k]} onChange={e=>setCommand(c=>({...c,[k]:e.target.value}))}/></Field>)}</>}<button disabled={busy} className="btn-primary">{busy?'Working…':'Confirm'}</button></form></Modal>}
    {settingsOpen&&config&&<Modal title="Sales settings" onClose={()=>setSettingsOpen(false)}><form className="space-y-4" onSubmit={async e=>{e.preventDefault();try{await api.patch('/sales/settings',{separate_approver:settings.separate_approver,currencies:settings.currencies,taxes:settings.taxes,prefixes:settings.prefixes});setSettingsOpen(false);void load();}catch(e){setError((e as Error).message);}}}><ErrorBox error={error}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={settings.separate_approver} onChange={e=>setSettings(s=>({...s,separate_approver:e.target.checked}))}/>Require a different approver</label><p className="text-sm text-fg-muted">Amounts use half-up rounding per line; milestones use the gross contract value.</p>{Object.keys(settings.currencies||{}).map(k=><Field key={k} title={`${k} decimal places`}><input className="input-field" type="number" min={0} max={4} value={settings.currencies[k]} onChange={e=>setSettings(s=>({...s,currencies:{...s.currencies,[k]:Number(e.target.value)}}))}/></Field>)}<Field title="Tax rates (comma separated)"><input className="input-field" value={(settings.taxes||[]).join(',')} onChange={e=>setSettings(s=>({...s,taxes:e.target.value.split(',').map(Number)}))}/></Field>{Object.entries(settings.prefixes||{}).map(([k,v])=><Field key={k} title={`${label(k)} prefix`}><input className="input-field" value={String(v)} onChange={e=>setSettings(s=>({...s,prefixes:{...s.prefixes,[k]:e.target.value}}))}/></Field>)}<button className="btn-primary">Save settings</button></form></Modal>}
  </div>;
}
function DataTable({rows}:{rows:Row[]}){if(!rows.length)return <p className="text-sm text-fg-muted">No records.</p>;const keys=Object.keys(rows[0]);return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border bg-surface-secondary">{keys.map(k=><th className="px-3 py-2" key={k}>{label(k)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-b border-border">{keys.map(k=><td key={k} className="max-w-sm whitespace-pre-wrap break-words px-3 py-2">{value(r[k])}</td>)}</tr>)}</tbody></table></div>;}
